### ISSUE TITLE
Debug help

### ISSUE THREAD

**Issue by Julesaiyy** [SongW-SW/COSMIC#1]
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    subgraph.build()
  File "/root/COSMIC/utils_mp.py", line 180, in build
    self.neighbor = self.ppr.search_all(self.node_num, self.path)
  File "/root/COSMIC/utils_mp.py", line 110, in search_all
    list(pool.imap_unordered(self.process(path), list(range(node_num)), chunksize=1000))
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: './subgraph/CoraFull/ppr0'

Thank you very much for your work, what should I do to fix it ?

**Comment by SongW-SW** [comment]
Thanks for pointing out this. It should be caused by noting creating the directory. I have updated the code in train.py from line 61. Now it should work. You can also manually create the directory.
